# Generated by Django 4.2.6 on 2023-10-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='valor_g',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Grande'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='valor_m',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Média'),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='valor_p',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor Pequena'),
        ),
    ]
