# Generated by Django 4.2.6 on 2023-10-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_rename_fone_cliente_telefone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor_p', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor P')),
                ('valor_m', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor M')),
                ('valor_g', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor G')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
