# Generated by Django 4.2.6 on 2023-10-20 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_pizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
