# Generated by Django 4.2.6 on 2023-10-27 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_alter_endereco_numero'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo_pagamento', models.CharField(choices=[('Dinheiro', 'Dinheiro'), ('Debito', 'Debito'), ('Credito', 'Credito'), ('Pix', 'Pix')], max_length=15)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='cadastros.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='ItensPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField()),
                ('tipo_item', models.CharField(max_length=10)),
                ('quantidade', models.IntegerField()),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItensPedido', to='cadastros.pedido')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ItensPedido', to='cadastros.pizza')),
            ],
        ),
    ]
